################################################################################
# Some global configuration
################################################################################
global:

  server:
    # telnet connection
    host: localhost
    port: 10011
    name: query_username
    pass: query_password

################################################################################
# Feature specific configuration
################################################################################
features:

  # Kick clients with unwanted names
  UsernameBlacklist:
    enable: True
    channel-whitelist: []
    channel-blacklist: []
    client-whitelist: []
    client-blacklist: []

    name_blacklist:
      # Blacklisted usernames as RegEx
      - "(.*)n[i!1](g+)er(.*)"
      - "(.*)n[a@]z[i!1](.*)"


  # Move clients on specific events
  AutoMove:
    enable: True
    channel_whitelist: []
    channel_blacklist: []
    client_whitelist: []
    client_blacklist: []


  # Detect musicbots (by continuous transmission)
  MusicbotDetect:
    enable: True
    channel_whitelist: []
    channel_blacklist: []
    client_whitelist: []
    client_blacklist: []

    # Delay in runticks
    detect_after: 5
