################################################################################
#
#  Aloha fellow user,
#  please read the documentation about the configuration of this tool to ensure
#  that you understand what's happening here on this site:
#
#  https://github.com/HWDexperte/ts3observer/wiki/Configuration
#
################################################################################
# Some global configuration
################################################################################
global:
  telnet:
    host: localhost
    port: 10011
    user: query_username
    pass: query_password
    serv: 1

################################################################################
# Feature specific configuration
################################################################################
features:

  UsernameBlacklist:
    enable: True
    channel-whitelist: []
    channel-blacklist: []
    client-whitelist: []
    client-blacklist: []

    name_blacklist:
      - "(.*)n[i!1](g+)er(.*)"
      - "(.*)n[a@]z[i!1](.*)"


  IdleManagement:
    enable: True
    channel_whitelist: []
    channel_blacklist: []
    client_whitelist: []
    client_blacklist: []

    on_idle:
      delay: 15


  MusicbotDetect:
    enable: True
    channel_whitelist: []
    channel_blacklist: []
    client_whitelist: []
    client_blacklist: []
