################################################################################
#
#  Aloha fellow user,
#  please read the documentation about the configuration of this tool to ensure
#  that you understand what's happening here on this site:
#
#  https://github.com/HWDexperte/ts3observer/wiki/Configuration
#
################################################################################
# Some global configuration
################################################################################
global:
  work_interval: 1
  telnet:
    host: localhost
    port: 10011
    user: query_username
    pass: query_password
    serv: 1
    display_name: "ts3observer"

################################################################################
# Feature specific configuration
#
# Please read here for the complete documentation of configure features:
# https://github.com/HWDexperte/ts3observer/wiki/Features
################################################################################
features:

  Base:
    rules:
      channel_whitelist: []
      channel_blacklist: []
      group_whitelist: []
      group_blacklist: []
      client_whitelist: []
      client_blacklist: []

#####
# Miscellaneous Features

  Test:
    enable: False
    execute:
      action: kick
      reasonid: 5
      reason: "Kicked by Aliens!"

  UsernameBlacklist:
    enable: False
    name_blacklist:
      - "(.*)n[i!1](g+)er(.*)"
      - "(.*)n[a@]z[i!1](.*)"
    execute:
      action: kick
      reasonid: 5
      reason: "Bad username"

  MusicbotDetection:
    enable: False
    execute:
      action: kick
      message: "Du bist ein Musikbot"
      m_delay: 5

#####
# Features to handle ways of idling

  OnAway:
    enable: False
    execute:
      action: kick
      reasonid: 5
      reason: "Away for too long!"

  OnIdle:
    enable: False
    execute:
      action: kick
      reasonid: 5
      reason: "Idled too long!"

  OnMute:
    enable: False
    execute:
      action: kick
      reasonid: 5
      reason: "Muted too long!"

  OnDeaf:
    enable: False
    execute:
      action: kick
      reasonid: 5
      reason: "Deaf too long!"
