################################################################################
#
#  Aloha fellow user,
#  please read the documentation about the configuration of this tool to ensure
#  that you understand what's happening here on this site:
#
#  https://github.com/HWDexperte/ts3observer/wiki/Configuration
#
################################################################################
# Some global configuration
################################################################################
global:
  telnet:
    host: localhost
    port: 10011
    user: query_username
    pass: query_password
    serv: 1

################################################################################
# Feature specific configuration
#
# Please read here for the complete documentation of configure features:
# https://github.com/HWDexperte/ts3observer/wiki/Features
################################################################################
features:

  Base:
    rules:
      channel_whitelist: [5, 6]
      channel_blacklist: []
      group_whitelist: []
      group_blacklist: []
      client_whitelist: []
      client_blacklist: []

#####
# Miscellaneous Features

  UsernameBlacklist:
    enable: True
    name_blacklist:
      - "(.*)n[i!1](g+)er(.*)"
      - "(.*)n[a@]z[i!1](.*)"
    execute:
      delay: 0
      action: kick
      from: server

#####
# Features to handle ways of idling

  OnAway:
    enable: True
    execute:
      s_delay: 15
      action: move
      to: 4
      move_back: True

  OnIdle:
    enable: True
    execute:
      m_delay: 15
      action: kick
      from: server

  OnMute:
    enable: True
    execute:
      s_delay: 15
      action: move
      to: 4
      move_back: False

  OnDeaf:
    enable: True
    execute:
      s_delay: 15
      action: move
      to: 4
      move_back: True
